// Warning: Everything below this line and above GENERATED_BODY() was auto-generated by Unreal. Don't change it.

#pragma once

#include "Core.h" // can use Core.h or CoreMinimal.h
#include "Kismet/BlueprintFunctionLibrary.h"
#include "UMyBlueprintFunctionLibrary.generated.h"

/**
 * 
 */
UCLASS()
class BLUEPRINTEXAMPLE_API UMyBlueprintFunctionLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

	// The UBlueprintFunctionLibrary class is a base class for any function libraries exposed to blueprints.
	// Methods in subclasses are expected to be static.
	// Note that the class name begins with U, even though it doesn't match the header filename.

	public:
		UFUNCTION(BlueprintCallable, Category = "MyBlueprintFunctionLibrary")
		static FString GetHappyMessage();

		// Saves text to filename of your choosing, make sure include whichever file extension you want in the filename, 
		// ex: SelfNotes.txt . Make sure to include the entire file path in the save directory, ex: C:\MyGameDir\BPSavedTextFiles 
		UFUNCTION(BlueprintCallable, Category = "MyBlueprintFunctionLibrary")
		static bool SaveStringTextToFile(FString SaveDirectory, FString FileName, FString SaveText, bool AllowOverWriting = false);

};
