// *** Warning: Everything below this line and above GENERATED_BODY() was auto-generated by Unreal. Be careful making changes. ***

#pragma once

#include "Core.h" // can use Core.h or CoreMinimal.h
#include "Kismet/BlueprintFunctionLibrary.h"
#include "UMyBlueprintFunctionLibrary.generated.h"

/**
 * 
 */
UCLASS()
class BLUEPRINTEXAMPLE_API UMyBlueprintFunctionLibrary : public UBlueprintFunctionLibrary 
{
	GENERATED_BODY()

	// *** It's safe to make changes now. ***
	// Note that the auto-generated class name always begins with U, even if it doesn't match the header filename.
	// This example uses the UBlueprintFunctionLibrary class. It's a base class for any function libraries exposed to Blueprints.
	// Methods in UBlueprintFunctionLibrary are expected to be static.

	public:
		// Just prints a string.
		UFUNCTION(BlueprintCallable, Category = "MyBlueprintFunctionLibrary")
		static FString GetHappyMessage();

		// Saves text input to a file.
		UFUNCTION(BlueprintCallable, Category = "MyBlueprintFunctionLibrary")
		static bool SaveStringTextToFile(FString SaveDirectory, FString FileName, FString SaveText, bool AllowOverWriting = false);
};
